import 'dotenv/config';

const EXPO_PUBLIC_MOMO_PARTNER_CODE = process.env.EXPO_PUBLIC_MOMO_PARTNER_CODE;
const EXPO_PUBLIC_MOMO_SECRET_KEY = process.env.EXPO_PUBLIC_MOMO_SECRET_KEY;
const EXPO_PUBLIC_MOMO_ACCESS_KEY = process.env.EXPO_PUBLIC_MOMO_ACCESS_KEY;

module.exports = ({ config }) => {
  config.extra.EXPO_PUBLIC_MOMO_PARTNER_CODE = EXPO_PUBLIC_MOMO_PARTNER_CODE;
  config.extra.EXPO_PUBLIC_MOMO_SECRET_KEY = EXPO_PUBLIC_MOMO_SECRET_KEY;
  config.extra.EXPO_PUBLIC_MOMO_ACCESS_KEY = EXPO_PUBLIC_MOMO_ACCESS_KEY;
  return config;
};
