const SCREEN_NAME = {
  HOME: 'HOME',
  CATEGORIES: 'CATEGORIES',
  CART: 'CART',
  ACCOUNT: 'ACCOUNT',
  NOTIFICATIONS: 'NOTIFICATIONS',
  SEARCH: 'SEARCH',
  SEARCH_NAVIGATOR: 'SEARCH_NAVIGATOR',
  FILTER_SCREEN: 'FILTER_SCREEN',
};

export { SCREEN_NAME };
