const SCREEN_NAME = {
  HOME: 'HOME',
  CATEGORIES: 'CATEGORIES',
  CART: 'CART',
  ACCOUNT: 'ACCOUNT',
  NOTIFICATIONS: 'NOTIFICATIONS',
  SEARCH: 'SEARCH',
  SEARCH_NAVIGATOR: 'SEARCH_NAVIGATOR',
  FILTER_SCREEN: 'FILTER_SCREEN',
  BOOK_DETAIL_NAVIGATOR: 'BOOK_DETAIL_NAVIGATOR',
  BOOK_DETAIL_SCREEN: 'BOOK_DETAIL_SCREEN',
};

export { SCREEN_NAME };
